# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
image: docker:stable

services:
- docker:dind

variables:
  DOCKER_USERNAME: andreabenf
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  
before_script:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-backend:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building backend docker image..."
    - docker build --pull -f ./backend/Dockerfile -t $DOCKER_USERNAME/ci_entrega_02:backend ./backend

build-frontend:      
  stage: build
  script:
    - echo "Building frontend docker image..."
    - docker build -f ./frontend/Dockerfile -t $DOCKER_USER/entrega02_frontend:ci_entrega_02:frontend ./frontend

test-frontend:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Running the frontend tests..."
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Success on the frontend tests"

test-backend:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Running the backend tests..."
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Success on the backend tests"

deploy-backend:      
  stage: deploy
  script:
    - echo "Deploying backend..."
    - docker push $DOCKER_USER/entrega02_backend:ci_entrega_02:backend

deploy-frontend:      
  stage: deploy
  script:
    - echo "Deploying frontend..."
    - docker push $DOCKER_USER/entrega02_frontend:ci_entrega_02:frontend


